feat: update package structure and size

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -28,6 +28,14 @@ jobs:
       - name: Install dependencies
         run: npm install
 
+      - name: Verify template structure
+        run: |
+            if [ ! -d "template" ]; then
+              echo "Template directory is missing!"
+              exit 1
+            fi
+            chmod +x ./template/setup.js  
+
       - name: Build
         run: npm run build
 
